### ISSUE TITLE
PHP 7.0 support in Ubuntu 16.04 (Xenial)

### ISSUE THREAD

**Issue by aparod** [geerlingguy/ansible-role-php#122]
It appears Ubuntu has updated to PHP 7.0 in the 16.04 (Xenial) release.  I'm not sure what all has changed between the versions, but I did notice that Ubuntu installs the 7.0 configuration files in `/etc/php/7.0`, whereas this project installs its files in `/etc/php5`.  Please consider updating the paths and checking how much the configuration options have changed, if at all.

**Comment by oxyc** [comment]
For now, to get it working you need to change them yourself. I have no idea what the plan is for supporting this out of the box though.

```yaml
php_version: "7.0"
php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php7.0-gd
  - php7.0-curl
  - php7.0-imap
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - php7.0-mbstring
php_mysql_package: php7.0-mysql
php_fpm_daemon: php7.0-fpm
php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/apache2
  - /etc/php/7.0/cli
php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/apache2/conf.d
  - /etc/php/7.0/cli/conf.d
php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"
```
