### ISSUE TITLE
No Package matching 'php-imap'

### ISSUE THREAD

**Issue by Sispheor** [geerlingguy/ansible-role-php#133]
You need to add the epel dependencies in meta I think.

**Comment by geerlingguy** [comment]
This is on CentOS, I believe? Would it be on 6 or 7 that you hit this error?

**Comment by Sispheor** [comment]
Centos 7. Not tested on 6
Le 1 juin 2016 11:10 PM, "Jeff Geerling" <notifications@github.com> a
écrit :

**Comment by geerlingguy** [comment]
I'll test further to make sure that's not the only package that would require epel; thanks!

**Comment by Lusitaniae** [comment]
Just in case its related,
I see the same thing with php-opcache.

I'm using CentOS 6, with the docker image from this role: chrismeyersfsu.provision_docker

and I get this when installing php packages

"No package matching 'php-opcache' found available, installed or updated", "rc": 126, "results": ["No package matching 'php-opcache' found available, installed or updated"

**Comment by jiv-e** [comment]
I have the same issue on Centos 7. This box: https://atlas.hashicorp.com/centos/boxes/7

**Comment by jiv-e** [comment]
Found help here: https://www.cyberciti.biz/faq/installing-rhel-epel-repo-on-centos-redhat-7-x/
$ yum -y install epel-release
$ yum repolist

After this it seems to work.

**Comment by jiv-e** [comment]
Easy way to fix this in your playbook:
```
  pre_tasks:
    - name: Install EPEL repo
      yum:
        name: epel-release
        state: present
        update_cache: yes
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.php }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.php-mysql }
```
