### ISSUE TITLE
php-fpm cannot start on CentOS 7

### ISSUE THREAD

**Issue by badgio** [geerlingguy/ansible-role-php#151]
/lib/init/vars.sh is included in fpm-init.j2 but does not exist on CentOS Linux 7 (Core).

May affect all RHEL based distros
https://github.com/buddycloud/deprecated-buddycloud-server/issues/69
https://github.com/elastic/logstash-forwarder/issues/75

```
TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ***
fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "Job for php-fpm.service failed because the control process exited with error code. See \"systemctl status php-fpm.service\" and \"journalctl -xe\" for details.\n"}
```

```
[user@host ~]$ sudo systemctl status php-fpm.service
● php-fpm.service - LSB: starts php-fpm
   Loaded: loaded (/etc/rc.d/init.d/php-fpm)
   Active: failed (Result: exit-code) since Mon 2016-09-26 11:09:48 BST; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 28981 ExecStart=/etc/rc.d/init.d/php-fpm start (code=exited, status=1/FAILURE)

Sep 26 11:09:48 host systemd[1]: Starting LSB: starts php-fpm...
Sep 26 11:09:48 host php-fpm[28981]: /etc/rc.d/init.d/php-fpm: line 30: /lib/init/vars.sh: No such file or directory
Sep 26 11:09:48 host systemd[1]: php-fpm.service: control process exited, code=exited status=1
Sep 26 11:09:48 host systemd[1]: Failed to start LSB: starts php-fpm.
Sep 26 11:09:48 host systemd[1]: Unit php-fpm.service entered failed state.
Sep 26 11:09:48 host systemd[1]: php-fpm.service failed.
```

Current pre_tasks to get this working

```
  pre_tasks:
    - name: Ensure redhat-lsb-core is installed
      yum: name=redhat-lsb-core state=present
    - name: Ensure /lib/init directory exists
      file: path=/lib/init state=directory
    - stat: path=/lib/init/vars.sh
      register: vars_sh_file
    - name: Ensure /lib/init/vars.sh exists
      file: path=/lib/init/vars.sh state=touch owner=root group=root mode=0555
      when: not vars_sh_file.stat.exists
```

**Comment by badgio** [comment]
Current pre_tasks to get this working

```
  pre_tasks:
    - name: Install redhat-lsb-core
      yum: name=redhat-lsb-core state=present
    - name: Ensure /lib/init config directory exists.
      file:
        path: /lib/init
        state: directory
    - stat: path=/lib/init/vars.sh
      register: varssh_file
    - name: Ensure /lib/init/vars.sh exists
      file: path=/lib/init/vars.sh state=touch owner=root group=root mode=0555
      when: not varssh_file.stat.exists
```

**Comment by geerlingguy** [comment]
Hmm... the Travis build begs to differ: https://travis-ci.org/geerlingguy/ansible-role-php (see first test under centos7).

I'm running a few CentOS 7 servers using FPM with either Nginx or Apache (also, Drupal VM is set to use FPM by default) without any issues. I start from the CentOS minimal x86_46 ISO in all cases... maybe the environment your using doesn't have the same layout as a minimal server install?

**Comment by badgio** [comment]
The environment is built from [CentOS-7-x86_64-Minimal-1511](http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso).

I've created a new install from the ISO, and a docker centos:7 image container, getting the same result. /lib/init does not exist on either for me.

**Comment by geerlingguy** [comment]
@badgio - It looks like in my Docker test container, I install the `initscripts` package, which contains functions that are used by a lot of different init scripts... I'm guessing that's also installed as a prerequisite when I do the packer build of the base image I use for my CentOS 7 servers.

**Comment by badgio** [comment]
Unfortunately not part of the initscripts package.

I'm installing php from source and the task which copies the template is not covered by those tests, it's in install-from-source.yml: "Ensure php-fpm init script is installed."

**Comment by geerlingguy** [comment]
Potentially related? https://github.com/geerlingguy/ansible-role-php/pull/162

The package installer should install the php-fpm init script/unit file :/

**Comment by 2autunni** [comment]
Same problem, solved adding 
  - php56-php-fpm
  - php-fpm

to variable "php_packages"

**Comment by jyaworski** [comment]
@geerlingguy I've reproduced this on Amazon Linux 2. I'm compiling from source with systemd enabled in configure.

**Comment by jyaworski** [comment]
When you compile with systemd, a unit file is generated per here:

https://github.com/php/php-src/blob/master/sapi/fpm/php-fpm.service.in

Instead of a template, when compiling from source it may be better to copy the init file or service file from here.

**Comment by johnyserpa** [comment]
Got this error too in a Vagrant machine with your image: `geerlingguy/centos7`

I'm also adding epel repo from your other role.

My `group_vars` file:
```
# geerlingguy.php-versions
php_version: '7.2'

# geerlingguy.php
php_packages: 
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
  - php-pecl-apcu
  - php-xml
  - php-mcrypt
php_webserver_daemon: "nginx"
php_enablerepo: "epel,remi-php72"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
```
My playbook:
```
---
- hosts: web
  become: true
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php
```

Error:
```
TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ********************************************************************************
fatal: [web1]: FAILED! => {"changed": false, "msg": "Could not find the requested service php-fpm: host"}
	to retry, use: --limit @/home/vagrant/ansible/web.retry
```

Any idea?
