### ISSUE TITLE
Undefined errors Ubuntu 16.04 w/ Ansible 2.2.0

### ISSUE THREAD

**Issue by christophermancini** [geerlingguy/ansible-role-php#160]
I am getting undefined errors on Ubuntu 16.04 running Ansible 2.2.0, I forked the repo and no matter what I try, I cannot get it to progress past this without explicitly defining variables...

It dies here:
```
- name: Delete APCu configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc and php_package_install.changed
  notify: restart webserver
```

There is a check for the var to see if it is defined, if not, it defines it:

```
- name: Define php_extension_conf_paths.
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined
```

The output:
```
TASK [ansible-role-php : Define php_extension_conf_paths test] *****************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
...
TASK [ansible-role-php : Delete APCu configuration file if this role will provide one.] ***
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'php_extension_conf_paths' is undefined"}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry
```

I modified the check for the var to:
```
- name: Define php_extension_conf_paths test
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: not php_extension_conf_paths or php_extension_conf_paths is undefined or php_extension_conf_paths is not defined
```

and it didn't change the outcome, that task is still skipped and the undefined error persists. I tried removing the `when` clause altogether and the same result:

```
- name: Define php_extension_conf_paths test - no when
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
...
TASK [ansible-role-php : Define php_extension_conf_paths test - no when] *******
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
...
TASK [ansible-role-php : Delete APCu configuration file if this role will provide one.] ***
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'php_extension_conf_paths' is undefined"}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry
```

I don't understand what is happening. The code does not do this on CentOS 7.2 with Ansible 2.2.
