### ISSUE TITLE
php-fpm socket user and group on centos 7 (nginx)

### ISSUE THREAD

**Issue by 2autunni** [geerlingguy/ansible-role-php#166]
In my playbook using 
>php_fpm_listen: "/dev/shm/php.socket"
php_fpm_pool_user: nginx
php_fpm_pool_group: nginx

when I restart php-fpm the socket is recreated with owner and group "root",  so nginx stop working and returns a 502 error.

I resolve this by setting:
>listen.owner = nginx
listen.group = nginx
listen.mode = 0660

in /etc/php-fpm.d/www.conf.

**Comment by eiriksm** [comment]
Here is another tip:

As it also is stated in the README:

>If you'd like to manage additional settings, you can do so either by replacing the file with your own template or using lineinfile

Specifically, this is what I used in my setup, and it works like you are describing.

```
- name: Configure php-fpm
      lineinfile:
        dest: "{{ php_fpm_pool_conf_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^listen.owner.?=.+$"
          line: "listen.owner = www-data"
        - regexp: "^listen.group.?=.+$"
          line: "listen.group = www-data"
        - regexp: "^listen.mode.?=.+$"
          line: "listen.mode = 0660"
```
