### ISSUE TITLE
Enable catch_workers_output for php-fpm

### ISSUE THREAD

**Issue by HMAZonderland** [geerlingguy/ansible-role-php#173]
I use this role to setup a development vm with also your nginx role. I want php-fpm to log its errors through to nginx. To make this happend the php-fpm setting `catch_workers_output` should be enabled which is not enabled by default. This setting should be set in the `www.conf` file

**Comment by longwave** [comment]
The documentation notes you can do this with `lineinfile`. Add something like this to your playbook:

```
- name: Set catch_workers_output in php-fpm pool.
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "^catch_workers_output.?=.+$"
    line: "catch_workers_output = yes"
    state: present
  notify: restart php-fpm
```

**Comment by phizev** [comment]
I only had to tweak the regex a little, or it would just append the line to the end of the file.
```
- name: Set catch_workers_output in php-fpm pool.
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "^;catch_workers_output.*$"
    line: "catch_workers_output = yes"
    state: present
  notify: restart php-fpm
```
