### ISSUE TITLE
Error installing modules for php 7.1

### ISSUE THREAD

**Issue by jcornide** [geerlingguy/ansible-role-php#177]
Hi, 

I'm trying to install php 7.1 using the remi repositories. The php installation itself goes fine, but in the next step I get this error:
`failed: [192.168.56.150] => (item=cli,common,devel,fpm,gd,ldap,mbstring,mcrypt,mysqlnd,opcache,pdo,pear,pecl-uploadprogress,process,xml) => {"changed": false, "failed": true, "item": "cli,common,devel,fpm,gd,ldap,mbstring,mcrypt,mysqlnd,opcache,pdo,pear,pecl-uploadprogress,process,xml", "rc": 0, "results": ["All packages providing php-cli are up to date"]}
msg: No Package matching 'common' found available, installed or updated`

Here's my defaults configuration:
```
# Select php version (php | php55 | php56 | php70 | php71)
#
#    | package name | version | base | ius | webtatic | remi |
#    | -            | -       | -    | -   | -        | -    |
#    |php           | 5.4.x   | ok   |     |          | ok   |
#    |php55         | 5.5.x   |      | ok  | ok       | ok   |
#    |php56         | 5.6.x   |      | ok  | ok       | ok   |
#    |php70         | 7.0.x   |      | ok  | ok       | ok   |
#    |php71         | 7.1.x   |      |     |          | ok   |
#
# Be extra careful when you choose php version.
# Not every repository have the corresponding php version. Check the table above.
php_version: php71

# EPEL only provides software not in the CentOS and RHEL official repositories, IUS and Remi provide newer versions of software already in the official repositories (like MySQL and PHP).

# The IUS repository provides newer versions of software in the official CentOS and RHEL repositories. The IUS repository depends on the EPEL repository.
# Package names in the IUS repository are not the same as the package names used in the official repositories. This helps avoid unintentional conflicts or software version updates.
# Note: Because IUS uses different package names from the official repositories, IUS is recommended over Remi

# The Remi repository provides newer versions of software in the core CentOS and RHEL repositories. The Remi repository depends on the EPEL repository.
# Package names in the Remi repository are the same as the package names used in the official repositories. This can result in inadvertent package upgrades when running an update with yum, so use the Remi repository with care.
# Note: Because Remi uses the same package names as the official repositories, Remi is not recommended
# Info: remi wizard: http://rpms.remirepo.net/wizard/

# Choose repository (base | ius | webtatic | remi)
#
# ius and remi needs epel repo, epel will be installed automatically if you choose one of these two.
# If you are using php (php 5.4) use the base repo, otherwise I suggest the isu repository.
repository: remi

# Add or remove php modules (do not include php itself)
php_modules:
  - cli
  - common
  - devel
  - fpm
  - gd
  - ldap
  - mbstring
  - mcrypt
  - mysqlnd
  - opcache
  - pdo
  - pear
  - pecl-uploadprogress
  - process
  - xml
```

**Comment by geerlingguy** [comment]
@jcornide - Interesting... are you using this role (`geerlingguy.php`)? Or maybe some other role?

I don't think there's any `php_modules` variable available in this role.

**Comment by geerlingguy** [comment]
This role _does_ have a `php_packages` variable... but nothing about modules.

**Comment by andrew-werdna** [comment]
Hey @geerlingguy thanks for all these awesome packages! I had a quick question, I am trying to install php7.1 also, (using Apache and on Debian/Ubuntu machine), when I use your role like so

```
        - role: geerlingguy.apache
        - role: geerlingguy.php
          php_version: "7.1"
          php_packages:
            - php7.1-common
            - php7.1-intl
            - php7.1-cli
            - php7.1-dev
            - php7.1-fpm
            - libpcre3-dev
            - php7.1-gd
            - php7.1-curl
            - php7.1-imap
            - php7.1-json
            - php7.1-opcache
            - php7.1-xml
            - php7.1-mbstring
            - php7.1-zip
          php_date_timezone: "America/Chicago"
          php_mysql_package: php7.1-mysql

        - role: geerlingguy.apache-php-fpm
        - role: geerlingguy.composer
        - role: geerlingguy.mysql
        - role: geerlingguy.php-mysql
```

^ all goes well installing the php7.1 packages, however in a later step, (I believe it is something like 'ensure php packages are installed', it starts installing the 7.0 package set [and configuring the conf files with paths that have 7.0 in them]). I think this may be coming from the /vars/Debian.yml

 Any thoughts? I am new to ansible so I realize I may be missing something, but my app needs to install some composer packages that depend on php7.1 :-/ (Symfony2.8.* app in the works)

**Comment by noplanman** [comment]
For PHP 7.1 on Debian, I'm using the repo provided by https://deb.sury.org/

Installation: https://packages.sury.org/php/README.txt

Then I use this role to perform the installation of all packages 👍

**Comment by jasperf** [comment]
@andrew-werdna I am having similar issues using this in `vars/main.yml`:

```
php_memory_limit: "512M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_version: "7.1"
php_packages:
  - php7.1-apcu
  - php7.1-common
  - php7.1-intl
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php-mbstring
  - php7.1-mcrypt
  - php7.1-opcache
  - php7.1-pdo
  - php7.1-xml
  - php7.1-mbstring
  - php7.1-zip
php_date_timezone: "Europe/Amsterdam"
php_mysql_package: php7.1-mysql
php_webserver_daemon: "nginx"

mysql_root_password: super-secure-password
mysql_databases:
  - name: example_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: example_user
    host: "%"
    password: similarly-secure-password
    priv: "example_db.*:ALL"

```
No idea yet if I should add a PPA in this case to avoid the errors like: `"msg": "No package matching 'php7.1-common' is available"`.
