### ISSUE TITLE
The conditional check 'php_opcache_conf_filename is not defined and ansible_distribution_version == "16.04"

### ISSUE THREAD

**Issue by TechFanDan** [geerlingguy/ansible-role-php#186]
Here is my role configuration:

 ```
roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-fpm
        - php7.0-common
        - php7.0-gd
        - php7.0-json
        - php7.0-cli
        - php7.0-curl
        - libapache2-mod-php7.0
        - php7.0-intl
        - php7.0-mbstring
        - php7.0-xml
      php_date_timezone: "America/Halifax"
      php_webserver_daemon: "apache2"
      php_mysql_package: php7.0-mysql
      php_conf_paths:
        - /etc/php/7.0/fpm
        - /etc/php/7.0/apache2
        - /etc/php/7.0/cli
      php_extension_conf_paths:
        - /etc/php/7.0/fpm/conf.d
        - /etc/php/7.0/apache2/conf.d
        - /etc/php/7.0/cli/conf.d
      php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"
```
Here is the error that I obtain when I attempt to run my playbook:

> TASK [geerlingguy.php : Define php_opcache_conf_filename (Ubuntu 16.04).] ******
> fatal: [192.168.2.33]: FAILED! => {"failed": true, "msg": "The conditional check 'php_opcache_conf_filename is not defined and ansible_distribution_version == \"16.04\"' failed. The error was: error while evaluating conditional (php_opcache_conf_filename is not defined and ansible_distribution_version == \"16.04\"): 'ansible_distribution_version' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/geerlingguy.php/tasks/main.yml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Define php_opcache_conf_filename (Ubuntu 16.04).\n  ^ here\n"}

This thread seems to talk about support back in mid 2016:
https://github.com/geerlingguy/ansible-role-php/issues/122

Hopefully, I didn't miss something obvious.
