### ISSUE TITLE
AWS PHP Conflict

### ISSUE THREAD

**Issue by clanstyles** [geerlingguy/ansible-role-php#188]
I'm receiving a lot of 
```
Error: php56-cli conflicts with php-cli-5.3.29-1.8.amzn1.x86_64\nError
```

If I type yum install php it works fine. What's causing this?

**Comment by clanstyles** [comment]
I'm using your PHP and Apache setup.

```
---
- hosts: websites
  remote_user: ec2-user
  # remote_user: user
  become: yes
  become_method: sudo

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

  vars_files:
  - vars/php.yml

  roles:
  - geerlingguy.apache
  - geerlingguy.php
```

The latest image:
```Amazon Linux AMI 2017.03.0 (HVM), SSD Volume Type - ami-22ce4934```
