### ISSUE TITLE
Can't get Apache to pick up mod_php settings using libapache2-mod-php7.0 instead of FPM

### ISSUE THREAD

**Issue by TechFanDan** [geerlingguy/ansible-role-php#189]
I'm currently using `ansible-role-php` but not `ansible-role-apache`. Should I be? Is this a requirement?

After a successful PHP install, Apache isn't parsing PHP files. I'm setting `fpm` to **false** and I did specify the package `libapache2-mod-php7.0`.

Current configuration:

```
roles:
    - role: geerlingguy.php
      php_version: "7.0"
      php_packages:
        - php7.0-fpm
        - php7.0-common
        - php7.0-gd
        - php7.0-json
        - php7.0-cli
        - php7.0-curl
        - libapache2-mod-php7.0
        - php7.0-intl
        - php7.0-mbstring
        - php7.0-xml
      php_webserver_daemon: "apache2"
      php_mysql_package: php7.0-mysql
      php_enable_php_fpm: false
```
