### ISSUE TITLE
Under Ansible 2.4, source build fails because '| failed' filter in when is always false

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php#219]
There must've been an upstream change in the way `command` output is registered, because in Ansible 2.3 and earlier, I could use the pattern:

```yaml
- name: Check if PHP is installed.
  command: which php
  changed_when: false
  failed_when: false
  register: php_installed

- name: Clone the PHP repository.
  git:
    repo: https://git.php.net/repository/php-src.git
    dest: "{{ php_source_clone_dir }}"
    version: "{{ php_source_version }}"
    accept_hostkey: yes
    depth: "{{ php_source_clone_depth }}"
  when: php_installed|failed
```

Specifically, `php_installed|failed` would return `false` and the dependent tasks would run.

In Ansible 2.4, I'm seeing failed builds (example: https://travis-ci.org/geerlingguy/ansible-role-php/jobs/278346316/config) indicating `failed` is always `false`. Or maybe my brain is just not working with all these double negatives.

In any case, a backwards-compatible and more commonly used check is the `rc` variable. So I will fix the source build hopefully by switching to this method.
