### ISSUE TITLE
Prevent webserver installation

### ISSUE THREAD

**Issue by eleftrik** [geerlingguy/ansible-role-php#222]
Is possibile to bypass webserver installation?

apache2 is installed, even if I set 
```

php_enable_webserver: false
php_webserver_daemon: ""    # false or "whatever"

```
The reason is this: I don't want to install neither Apache nor Nginx; after executing this role, I optionally will run another role to install Nginx and configure it (with more options).

Thanks

**Comment by FinBoWa** [comment]
This role doesn't install neither nginx or apache. 

per docs that boolean is used for:

"If your usage of PHP is tied to a web server (e.g. Apache or Nginx), leave this default value. If you are using PHP server-side or to run some small application, set this value to `false` so this role doesn't attempt to interact with a web server." 

Maybe the os image that you are using has apache ready there.

**Comment by eleftrik** [comment]
@FinBoWa I'm using `debian/jessie64` Vagrant box.
I destroyed the vm and recreated it.

When I initially `vagrant up`, neither Apache nor Nginx are installed:

`dpkg --get-selections | grep apache`
returns blank.

After running my playbook, based on geerlingguy.php role, Apache2 is installed:

`dpkg --get-selections | grep apache`
returns

apache2						install
apache2-bin					install
apache2-data					install
apache2-utils					install
libapache2-mod-php7.0				install

`service apache2 status`
returns

● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─forking.conf
   Active: active (running) since Thu 2017-10-19 16:51:40 GMT; 2min 19s ago
   CGroup: /system.slice/apache2.service
           ├─31445 /usr/sbin/apache2 -k start
           ├─31448 /usr/sbin/apache2 -k start
           ├─31449 /usr/sbin/apache2 -k start
           ├─31450 /usr/sbin/apache2 -k start
           ├─31451 /usr/sbin/apache2 -k start
           └─31452 /usr/sbin/apache2 -k start

Oct 19 16:51:37 jessie systemd[1]: Starting LSB: Apache2 web server...
Oct 19 16:51:40 jessie apache2[31431]: Starting web server: apache2.
Oct 19 16:51:40 jessie systemd[1]: Started LSB: Apache2 web server.



Here my playbook:

```

---
- hosts: all
  become: true
  roles:
    - role: geerlingguy.php
      php_packages:
        - php
        - php-cli
        - php-dev
        - php-fpm
        - php-bcmath
        - php-bz2
        - php-common
        - php-curl
        - php-dba
        - php-gd
        - php-gmp
        - php-imap
        - php7.0-imagick
        - php7.0-memcached
        - php7.0-redis
        - php-intl
        - php-json
        - php-ldap
        - php-mbstring
        - php-mcrypt
        - php-mysql
        - php-odbc
        - php-pgsql
        - php-pspell
        - php-soap
        - php-sqlite3
        - php-tidy
        - php-xml
        - php-xmlrpc
        - php-zip
        - php-opcache
        - php-xsl
      php_enable_webserver: false
      php_webserver_daemon: ""
...


```

Am I doing anything wrong?
Thanks for your support
