### ISSUE TITLE
PHP5 module is not activated in Apache2

### ISSUE THREAD

**Issue by derheap** [geerlingguy/ansible-role-php#23]
Tried the role on a mint server, php5 was installed, but not working in Apache2.

I added

```
- name: Enable PHP in Apache
  apache2_module: 
    state: present 
    name: php5
  notify: restart webserver
  when: php_enable_webserver
```

in configure.yml to fix it.
