### ISSUE TITLE
Configuration issues when using remi

### ISSUE THREAD

**Issue by vpassapera** [geerlingguy/ansible-role-php#230]
```
---
...
php_executable: "php71"
php_enablerepo: "remi"
php_packages_state: "latest"
php_use_managed_ini: true
php_memory_limit: "2048M"
php_packages:
  - php71-php-common
  - php71-php-cli
  - php71-php-mcrypt
  - php71-php-mbstring
  - php71-php-xml
  - php71-php-gd
  - php71-php-intl
  - php71-php-fpm
  - php71-php-opcache
  - php71-php-pecl-redis
  - php71-php-pecl-igbinary
  - php71-php-bcmath
  - php71-php-pecl-zip
  - php71-php-pecl-apcu
  - php71-php-pecl-apcu-bc
  - php71-php-opcache
  - php71-php-pecl-ssh2
  - php71-php-pecl-xdebug
  - php71-php-dbg
  - php71-php-pear
  - php71-php-posix
  - php71
```

```
---
- hosts: php-util
  become: true

  roles:
    - geerlingguy.repo-remi
    - geerlingguy.php
    - geerlingguy.composer
```

This configures items in `/etc/php.ini` however, remi loads configuration from `/etc/opt/remi/php71/php.ini`.

Same goes for extension configs, etc.

I will open a PR to allow those paths to be overwritten at the config level (moving them from `vars` to `defaults`.
