### ISSUE TITLE
The role does not have `become: true` at parts that usually require root access

### ISSUE THREAD

**Issue by Uwila** [geerlingguy/ansible-role-php#245]
For example:

When arriving at the step "Ensure PHP packages are installed" I get an error:

```
failed: [packages] (item=['php-cli', 'php']) => {"cache_update_time": 1528463800, "cache_updated": 
false, "changed": false, "item": ["php-cli", "php"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--
force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'php' -o APT::Install-Recommends=yes' 
failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock 
the administration directory (/var/lib/dpkg/), are you root?\n", "rc": 100, "stderr": "E: Could not open 
lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration 
directory (/var/lib/dpkg/), are you root?\n", "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock 
- open (13: Permission denied)", "E: Unable to lock the administration directory (/var/lib/dpkg/), are you 
root?"], "stdout": "", "stdout_lines": []}
```

It seems to me that the critical part of this message are the repeated messages `Permission denied` and `are you root?`.

I would suggest adding `become: true` to the tasks that require this (which are quite a lot), but perhaps I'm doing something wrong?

**Comment by Uwila** [comment]
I can run the role from the playbook rather than using the `include_role` module, and then `become: true` seems to work (it didn't work in combination with `include_role` for some reason)

**Comment by jleaders** [comment]
For  include role it looks like this:

```
  include_role:
    name: geerlingguy.php
    apply:
      become: yes
```

Note the "apply" is required. One of the problems with ansible is it has esoteric idiosyncracies.
Make sure you're on `ansible --version` > 2.7

_ALSO, make sure you do this for all other geerlingguy.php roles, such as php-version etc._
Further reading:
https://stackoverflow.com/questions/39183100/define-become-yes-per-role-with-ansible#39184357
https://docs.ansible.com/ansible/latest/modules/include_role_module.html

**Comment by elburro1887** [comment]
Thanks for the tip. This worked for me:

```
---
- hosts: my_host
  become: yes
  gather_facts: yes
  vars_files:
    - vars/php_apache.yml
  roles:
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.apache
    - geerlingguy.apache-php-fpm
```
