### ISSUE TITLE
"Ensure PHP packages are installed" Missing From Master?

### ISSUE THREAD

**Issue by paulrrogers** [geerlingguy/ansible-role-php#257]
When using master with Ubuntu 18.04 and PHP 7.3 it appears PHP is never actually installed. Is the "ensure ... installed" step missing or am I overlooking something?

```
- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
  with_items: "{{ php_packages }}"
  notify: restart webserver
```
