### ISSUE TITLE
Cannot install 2 versions of php?

### ISSUE THREAD

**Issue by aviatrix** [geerlingguy/ansible-role-php#259]
So i have the following setup on Debian 9.x 
```
- hosts: webservers
  remote_user: simpleton
  become_user: root
  become: yes
  become_method: su
  vars_files:
    - vars/php.yml
  roles:
    - geerlingguy.php-versions
    - role: geerlingguy.php
      vars:
        php_version: "7.2"
        php_fpm_port: 9072
    - role: geerlingguy.php
      vars:
        php_version: "7.0"
        php_fpm_port: 9070
```
and then my php vars :
```
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:{{ php_fpm_port }}"
php_fpm_listen_allowed_clients: "127.0.0.1"

#Packages
php_packages_extra:
  - php-mcrypt
  - php{{ php_version }}-mysql
  - php{{ php_version }}-soap
  - php{{ php_version }}-memcached
  - php{{ php_version }}-zip
  - php{{ php_version }}-intl
  - php{{ php_version }}-apcu
```

**Expected result** : 
  2 versions of php with fpm installed
**Actual result**
 Only the first version of php is installed properly.
 The second one (7.0) has no binary in the `/usr/sbin/` directory and the `/etc/php/7.0/fpm/php-fpm.conf` is missing as well. 

If i swap the places of the versions, the result is the same, php 7.0 installed properly, 7.2 missing

Note: I've noticed that php-versions playbook purges one of the php versions, however since i'm installing 2 versions AFTER the php-versions purge, 
everything should be ok, but it's not.

Also, if i install both php versions manually, all is good. 

Any ideas to what might cause this?
