### ISSUE TITLE
Preferred way to disable certain PHP extension 

### ISSUE THREAD

**Issue by till** [geerlingguy/ansible-role-php#265]
Thanks again for this role. Basically adding your roles into a playbook, server setup. 🎉 So thanks for that! :)

---

I had a question what you or anyone on here suggests if I need to disable php extensions. I see the role installs many, many of which I don't need and would like to get rid off. Just to trim PHP's footprint.

Also, somewhat related. I am using Apache and mod php, but I still have php-fpm running. Couldn't find much to disable features that I have no use for. Is anyone doing something like that?

**Comment by ezbik** [comment]
> but I still have php-fpm running.

same "issue" here. Add post-tasks into your playbook:

```
post-tasks:
 - name: stop php7.2-fpm
   systemd:
     state: stopped
     enabled: no
     masked: yes
     name: php7.2-fpm
```
