### ISSUE TITLE
php_sendmail_path variable doesn't work

### ISSUE THREAD

**Issue by 3e33** [geerlingguy/ansible-role-php#275]
```
    - name: php
      include_role:
          name: geerlingguy.php
      vars:
        php_default_version_debian: "7.2"
        php_sendmail_path: "/opt/mailhog/mhsendmail"

    - name: php-xdebug
      include_role:
        name: geerlingguy.php-xdebug
      vars:
        php_xdebug_version: 2.7.2
        php_xdebug_remote_enable: "true"
        php_xdebug_remote_connect_back: "true"
```

The rest of this seems to work except php_sendmail_path, none of the .ini files get updated with the value.
