### ISSUE TITLE
Debian 10 (Buster) - No package matching 'php7.0-common' is available"

### ISSUE THREAD

**Issue by luisnabais** [geerlingguy/ansible-role-php#281]
Hello.

I'm running Vagrant, using a Debian 10 Buster VM, which seems the official Vagrant box (debian/buster64), and when I try to use the role geerlingguy.php, I get the error:

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ************************************************************************************************************************************************
fatal: [debian]: FAILED! => {"changed": false, "msg": "No package matching 'php7.0-common' is available"}
```

Can you help, please? My playbook is this (it's a test I'm doing):
```
---
- hosts: localenv
  become: yes
  vars:
    - ntp_timezone: Europe/Lisbon
  roles:
    - { role: geerlingguy.repo-epel, when: ansible_os_family == "RedHat" }
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
```

Thanks a lot.
