### ISSUE TITLE
Build issues on Debian 9 stretch AMI

### ISSUE THREAD

**Issue by earchibald-lv** [geerlingguy/ansible-role-php#291]
1) `libmysqlclient-dev` is `default-libmysqlclient-dev` on Deb 9 stretch.
2) Documentation: `git` should listed in Dependencies for building from source.
3) I had to add `--without-sqlite3` and `--without-pdo-sqlite` to `php_source_configure_command` to work properly. Getting a current version of sqlite3 onto Debian 9 is a pain.

Play that I used for prep/patch:
```
---
- name: Install prerequisites and nginx
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: install nginx with apt
    package:
      name: nginx
      state: present
  - name: install git with apt
    package:
      name: git
      state: present
  - name: patch geerlingguy.php for Deb 9 stretch default-libmysqlclient-dev
    replace:
      path: .ansible/roles/geerlingguy.php/tasks/install-from-source.yml
      regexp: '^( *- )(libmysqlclient-dev)'
      replace: '\1default-\2'
```
