### ISSUE TITLE
Can't override debian.yml variables

### ISSUE THREAD

**Issue by MichaelMallett** [geerlingguy/ansible-role-php#30]
I'm driving myself a bit crazy trying to override the __php_packages variable in a variables file that I call in the playbook. It's just ignoring it and installing apache, which I don't want it to do. I can override others (php_enable_apc, php_enable_php_fpm), but something perhaps to do with the underscores?

I basically don't want it to install apache at all, I want to use a seperate role because I can't find a way to stop it using prefork

An extract of the playbook:

```
- name: Install base packages to new cloud server
  hosts: deploy
  user: root
  gather_facts: True

  vars_files:
    - "vars/lamp.yml"

  tasks:
    - name: Dump all vars
      action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
  roles:
      - { role: roles/geerlingguy.php }

```

The variables file

```
---
php_packages:
  - php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php-pear
  - php-apc
  - libpcre3-dev
# Start and enable the PHP fpm service.
php_enable_php_fpm: true
# Don't need APC in php 5.5 as it has opcode caching built into core
php_enable_apc: false
php_enable_webserver: false
```

**Comment by MichaelMallett** [comment]
I've also tried having the variables in the playbook, but they are still ignored. This is perhaps a problem with ansible variable precedence, but I've read numerous issues that say a playbook should override a roles default and vars file

```
  vars_files:
    - "vars/lamp.yml"
  vars:
    - __php_packages:
        - php5
        - php5-mcrypt
        - php5-cli
        - php5-common
        - php5-curl
        - php5-dev
        - php5-fpm
        - php5-gd
        - php-pear
        - php-apc
        - libpcre3-dev

  roles:
    - roles/geerlingguy.php
```
