### ISSUE TITLE
error: the role 'geerlingguy.php' was not found

### ISSUE THREAD

**Issue by eran101** [geerlingguy/ansible-role-php#308]
I tried to run the playbook in the [Ubuntu 18.04 LXC template](https://us.images.linuxcontainers.org/).
This is my playbook file content:

```
- hosts: localhost
  become: yes
  connection: local
  vars_files:
          - vars/main.yml
  roles:
    - { role: geerlingguy.php }
 ```

The vars/main.yml was created [according to this link](https://github.com/geerlingguy/ansible-role-php#example-playbook).

The error is: 
ERROR! the role 'geerlingguy.php' was not found in /home/ubuntu/ansible-role-php/roles:/home/ubuntu/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ubuntu/ansible-role-php

The error appears to be in '/home/ubuntu/ansible-role-php/lamp.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - { role: geerlingguy.php }
      ^ here
