### ISSUE TITLE
Two versions of php are installed

### ISSUE THREAD

**Issue by justas147** [geerlingguy/ansible-role-php#357]
When I set `php_default_version_debian` variable to install version `7.3` php 8.1 is also installed and gets set as the main version for php command. Does this suppose to happen or have I missed something? 

![image](https://user-images.githubusercontent.com/24777490/150295603-abce204a-c124-4997-b107-ada97eedd48a.png)

**Comment by racke** [comment]
Which distribution do you use on the target host?

**Comment by justas147** [comment]
Ubuntu 20

**Comment by justas147** [comment]
> Which distribution do you use on the target host?

Ubuntu 20

**Comment by tarantegui** [comment]
It is also happening to me in Ubuntu 18. My variable sets the version to 8.0 and a few days ago it was installing 8.0.14 and now is installing 8.1.2. Any idea to solve that?

**Comment by justas147** [comment]
I included a task to set the default php version after:
```
- name: Select default php version
  become: true
  alternatives:
    name: php
    path: "/usr/bin/php{{ php_default_version_debian }}"
```
