### ISSUE TITLE
How to install multiple versions of PHP on Redhat 8

### ISSUE THREAD

**Issue by marketier** [geerlingguy/ansible-role-php#381]
What syntax do I use to install multiple versions of PHP? Is the following correct?

```
---
- hosts: '{{inventory}}'
  become: true
  vars:
    php_version: '7.2'
  roles:
    - php_versions
    - php

- hosts: '{{inventory}}'
  become: true
  vars:
    php_version: '7.4'
  roles:
    - php_versions
    - php
```

Also, I'm seeing the following error after running the above:

`"stderr": "Error: Problems in request:\nmissing groups or modules: php:remi-7.4"`

Do I need to add the REMI to my repo first?

`sudo dnf install http://rpms.remirepo.net/enterprise/remi-release-8.rpm`

Thanks for your help in advance.
