### ISSUE TITLE
How to install PHP 8.1 on Amazon Linux 2?

### ISSUE THREAD

**Issue by ElijahLynn** [geerlingguy/ansible-role-php#382]
This is mostly a thread I can rubber duck on, and for others to search and find info on how to install PHP 8.1 on Amazon Linux 2.

**Comment by ElijahLynn** [comment]
Remi installs to a different `.ini` directory too, `/etc/opt/remi/php81/php.d`, so the lay down of this roles variables such as `php_max_execution_time` don't get laid down in the right place.

**Comment by ElijahLynn** [comment]
I had to also create a step to symlink `php` to `php81`.

**Comment by ElijahLynn** [comment]
I had to specify all the packages in `php_packages` with a `php81-` prefix, so e.g. `php81-php-gd`. o

**Comment by ElijahLynn** [comment]
I used this in our code to install PHP 8.1. We also have geerlingguy.php before this but I'm not sure if it is needed. 

```
  - role: build/roles/cms/galaxy/geerlingguy.php
    become: yes
    become_user: root
    php_enablerepo: remi-php81
    php_executable: php
    php_packages:
      - php81
      - php81-php-pecl-apcu
      - php81-php-mysqlnd
      - php81-php-cli
      - php81-php-gd
      - php81-php-opcache
      - php81-php-process
      - php81-php-pear
      - php81-php-xml
      - php81-php-mbstring
      # zip is required for Drush 10
      - php81-php-pecl-zip
      - php81-php-pecl-memcache
      - php81-php-sodium
```
