### ISSUE TITLE
Could not find the requested service php8.2-fpm: host

### ISSUE THREAD

**Issue by MateuszPrasal** [geerlingguy/ansible-role-php#393]
Hi ! 
I'm trying to use PHP 8.2 on Debian 11. PHP CLI works well, but I have a lot of problems to launch php-fpm. I'm using Nginx as webserver. During launching playbook, I'm receiving `Could not find the requested service php8.2-fpm: host` error. 
Below my Ansible config

```
php_enable_php_fpm: true
    php_version: "8.2"
    php_default_version_debian: "8.2"
    php_fpm_state: started
    php_fpm_enabled_on_boot: true
    php_packages:
      - "php8.2-curl"
      - "php8.2-mbstring"
      - "php8.2-mysql"
      - "php8.2-pdo"
      - "php8.2-zip"
      - "php8.2-soap"
      - php8.2-xml
      - php-redis
 ```
 
 I'd be glad for help :)
