### ISSUE TITLE
Support ondrej PPA for more recent php version

### ISSUE THREAD

**Issue by louim** [geerlingguy/ansible-role-php#49]
It would be awesome if there was an option to use php [5.4](https://launchpad.net/~ondrej/+archive/ubuntu/php5-oldstable), [5.5](https://launchpad.net/~ondrej/+archive/ubuntu/php5) and [5.6](https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6) from Ondřej Surý, which offer the latest PHP instead of the sometime older version from the official packages.

**Comment by geerlingguy** [comment]
This role supports those PPAs (and any other) out of the box, if you simply add them to your system prior to running the role/installing PHP. As an example, check out [this example](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L19-L30) from Drupal VM.

If you use a package installation, you can choose what PPA you want this way. Otherwise, if you'd like a precise/exact version, you can always [install from source](https://github.com/geerlingguy/ansible-role-php#installing-from-source) and get _exactly_ the version you need :)

**Comment by solomongifford** [comment]
We created a role named php-defaults that had the pattern:

In tasks/main.yml:
```
- name: Include defaults
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  ignore_errors: True

- name: Define php_packages (This will fail if the php version is not supported on this OS).
  set_fact:
    php_packages: "{{ php_package_list[php_version] }}"
    php_enablerepo: "{{ php_enablerepo_list[php_version] }}"

#this was needed for Debian 
- name: Add a Repo key (apt)
  apt_key: url={{ php_repo_key_url }}
  when: php_repo_key_url is defined

#This is needed for both Debian and Ubuntu.
- name: Enable a Repo (apt)
  apt_repository: repo={{ item }} state=present
  with_items: "{{ php_enablerepo | list }}"
  when: ansible_os_family == "Debian" and php_enablerepo|default('') != ''
```

Then in the vars directory we created multiple files, one for each os/version combo. For example, Ubuntu14.yml has:

```
---
php_version: php56
php_enablerepo_list:
  php70:
   - "ppa:ondrej/php"
  php56:
   - "ppa:ondrej/php"
  php55: ""
php_package_list:
  php70:
   - libapache2-mod-php7.0
   - php7.0
   - php7.0-dev
   - php7.0-mysql
   - php7.0-xml
   - php7.0-soap
   - php7.0-mcrypt
   - php7.0-cli
   - php-pear
   - php7.0-opcache
  php56:
   - libapache2-mod-php5.6
   - php5.6
   - php5.6-dev
   - php5.6-mysql
   - php5.6-xml
   - php5.6-soap
   - php5.6-mcrypt
   - php5.6-imap
   - php5.6-cli
   - php-pear
   - php5.6-opcache
  php55:
   - libapache2-mod-php5
   - php5
   - php5-dev
   - php5-mysql
   - php-xml-parser
   - php-soap
   - php5-imap
   - php5-mcrypt
   - php5-cli
   - php-pear
```

Changing the "php_version" variable from php56 to php70, for example, would install php70 instead of our default php56.

@geerlingguy, I assumed this type of addition would have been deemed outside the scope of the module.  If you'd rather include this logic, let me know and I can submit a PR.  It does make installing any version a breeze.
