### ISSUE TITLE
OpenSSL libraries

### ISSUE THREAD

**Issue by furester** [geerlingguy/ansible-role-php#67]
Installing from source with these vars:

``` yaml
...
php_install_from_source: true
php_source_version: "master"
```

i have an error during `configure` step that i could resolve adding packages to apt items:

``` yaml
- name: Ensure dependencies for building from source are installed (Debian).
  apt: "pkg={{ item }} state=installed"
  with_items:
...
    - libcurl4-openssl-dev
    - pkg-config
```

is it possible to add them in order to proper configure last php?
(fyi, i found information about how to solve this issue here: [serverfault.com/questions/415458](http://serverfault.com/questions/415458/php-error-cannot-find-openssls-evp-h))

i don't know what about CentOS or other rpm based distro.
