### ISSUE TITLE
www.conf pool

### ISSUE THREAD

**Issue by dsoriano** [geerlingguy/ansible-role-php#75]
Hello! First of all, thank you for your work.

I have a question about recents changes about the www.conf configuration: Why ? :)
I don't want to keep this file in the configuration and with these changes it's now complicated to remove it. Is there an option I missed to avoid the "Configure php-fpm pool" ?

Thanks for your help

**Comment by geerlingguy** [comment]
This was a rather controversial change (at least in my mind), and I actually took one of my sites offline (one that I didn't test in a pre-prod environment) for a couple minutes until I figured out I was using sockets and the role defaulted to a TCP port...

But with the way this is set up (`php_enable_php_fpm` to enable, plus only modify the existing file, don't force a special config file), it should be simple enough for the role's consumers to add a few configuration directives as-needed to make sure the changes are correct.

I'd consider a new variable like `php_manage_php_fpm_config`, maybe... but I didn't want to make this too complicated.

**Comment by dsoriano** [comment]
Thank you for your response,
I unserderstand the problem. If I can suggest something, perhaps it is simply possible to test the www.conf file existence. So you can keep compatibility with older version and the consumer is free to delete it if he wants to.

I'm not an expert but something like this : 

```
- stat: path="{{ php_fpm_pool_conf_path }}"
  register: default_conf_file

- name: Configure php-fpm pool (if enabled).
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
...
  when: (php_enable_php_fpm) and
        (default_conf_file.stat.exist == true)
  notify: restart php-fpm
```
Sorry, not tested ;)
